instances: 
  - id: 0
    instance_name: "Arnold AI"
    subscription_plan: null
    owner_id: null

workspaces:
  - id: 0 
    instance_id: 0
    workspace_name: "enMedD AI"
    workspace_description: "enMedD AI Workspace"
    use_custom_logo: false
    custom_logo: null
    custom_header_logo: null
    custom_header_content: null

teamspaces:
  - id: 0
    name: "Global"