apiVersion: v1
kind: Secret
metadata:
  name: danswer-secrets
type: Opaque
data:
  postgres_user: cG9zdGdyZXM= # "postgres" base64 encoded
  postgres_password: cGFzc3dvcmQ= # "password" base64 encoded
  postgres-password: cGFzc3dvcmQ=
  google_oauth_client_id: # You will need to provide this, use echo -n "your-client-id" | base64
  google_oauth_client_secret: # You