# The values in this file should be changed
apiVersion: v1
kind: Secret
metadata:
  name: danswer-secrets
type: Opaque
data:
  postgres_user: cG9zdGdyZXM= # "postgres" base64 encoded
  postgres_password: cGFzc3dvcmQ= # "password" base64 encoded
  google_oauth_client_id: MjcwNjk3ODEzMi1iMzZnb20wa2Fhb3I2MmlwYWt2dmRxdm91OGRic2d1cC5hcHBzLmdvb2dsZXVzZXJjb250ZW50LmNvbQ== # You will need to provide this, use echo -n "your-client-id" | base64
  google_oauth_client_secret: R09DU1BYLWlZbDBSN1ZvYnk0cjZJRUFmekRqdjhad0pnOGI= # You will need to provide this, use echo -n "your-client-id" | base64
